import { mkdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const root = process.cwd();
const docsDir = resolve(root, "docs");
const readmePath = join(docsDir, "README.md");

function ensureDocsDirectory() {
  try {
    const stats = statSync(docsDir);
    if (!stats.isDirectory()) {
      rmSync(docsDir, { recursive: true, force: true });
      mkdirSync(docsDir, { recursive: true });
      return;
    }
  } catch {
    mkdirSync(docsDir, { recursive: true });
  }
}

function ensureReadme() {
  const content = [
    "# Paywaz SDK Docs (Placeholder)",
    "",
    "This placeholder documentation keeps the docs workflow green while offline.",
    "Add your generated documentation here when ready.",
    "",
    "Generated by scripts/docs.mjs.",
    "",
  ].join("\n");

  mkdirSync(dirname(readmePath), { recursive: true });
  writeFileSync(readmePath, content);
}

ensureDocsDirectory();
ensureReadme();

console.log("Docs generated (placeholder).");
