import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const rootDir = process.cwd();
const openapiDir = path.resolve(rootDir, "openapi");

if (!existsSync(openapiDir)) {
  console.warn("OpenAPI directory not found; skipping SDK generation.");
  process.exit(0);
}

const openapiFiles = readdirSync(openapiDir)
  .filter((file) => /\.(ya?ml|json)$/i.test(file))
  .sort();

if (openapiFiles.length === 0) {
  console.warn("No OpenAPI files found; skipping SDK generation.");
  process.exit(0);
}

const selectedFile = path.resolve(openapiDir, openapiFiles[0]);
const source = readFileSync(selectedFile);
const stats = statSync(selectedFile);
const sha256 = createHash("sha256").update(source).digest("hex");

const summary = {
  sourcePath: path.relative(rootDir, selectedFile).replace(/\\/g, "/"),
  byteLength: stats.size,
  sha256,
};

const outputDir = path.resolve(rootDir, "src/generated");
mkdirSync(outputDir, { recursive: true });

const summaryPath = path.join(outputDir, "openapi-summary.ts");
const indexPath = path.join(outputDir, "index.ts");

const header = "// This file is generated by scripts/generate-sdk.ts. Do not edit manually.\n";
const summaryContents =
  header +
  `export const openapiSummary = ${JSON.stringify(summary, null, 2)} as const;\n` +
  "export type OpenAPISummary = typeof openapiSummary;\n";

writeFileSync(summaryPath, summaryContents);
writeFileSync(indexPath, `${header}export * from "./openapi-summary.js";\n`);

console.log(
  `Wrote OpenAPI summary for ${summary.sourcePath} (${summary.byteLength} bytes).`
);
