import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const specPath = path.resolve(__dirname, "../openapi/openapi.yaml");
const specContents = readFileSync(specPath, "utf8");
const specHash = createHash("sha256").update(specContents).digest("hex");

const generatedDir = path.resolve(__dirname, "../src/generated");
mkdirSync(generatedDir, { recursive: true });

const generatedFile = path.join(generatedDir, "index.ts");

const header = `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-sdk.mjs
// Source: openapi/openapi.yaml
// Spec hash (sha256): ${specHash}
`;

const generatedTypes = `${header}
export const OPENAPI_SPEC_HASH = "${specHash}";
export const OPENAPI_VERSION = "2025-01-01";
export const OPENAPI_BASE_URL = "https://api.paywaz.com";

export type GeneratedPaymentStatus = "pending" | "confirmed" | "settled" | "failed";

export interface GeneratedCreatePaymentRequest {
  amount: string;
  currency: string;
  destination: string;
  autoConvert?: boolean;
  metadata?: Record<string, unknown>;
}

export interface GeneratedPayment {
  id: string;
  status: GeneratedPaymentStatus;
  amount: string;
  currency: string;
  destination: string;
  transactionHash?: string | null;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export type GeneratedWebhookEventType =
  | "payment.pending"
  | "payment.confirmed"
  | "payment.settled"
  | "payment.failed";

export interface GeneratedWebhookEvent {
  id: string;
  type: GeneratedWebhookEventType;
  eventVersion: string;
  livemode: boolean;
  createdAt: string;
  data: {
    payment: GeneratedPayment;
  };
}
`.trimEnd();

writeFileSync(generatedFile, `${generatedTypes}\n`, "utf8");

console.log(`Generated ${path.relative(path.resolve(__dirname, ".."), generatedFile)} from OpenAPI (sha256: ${specHash}).`);
