import { createHash } from "crypto";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const specPath = path.join(repoRoot, "openapi", "openapi.yaml");
const hashPath = path.join(repoRoot, "openapi", "openapi.sha256");
const generatedDir = path.join(repoRoot, "src", "generated");
const metadataPath = path.join(generatedDir, "openapi-metadata.ts");

const specContents = readFileSync(specPath, "utf8");

const openApiSha256 = createHash("sha256")
  .update(specContents, "utf8")
  .digest("hex");

const header = [
  "# Generated by npm run generate:sdk",
  "# Do not edit manually.",
  "# This file captures the OpenAPI spec hash for sync checks.",
  "",
].join("\n");

writeFileSync(hashPath, `${header}${openApiSha256}\n`);

mkdirSync(generatedDir, { recursive: true });

const versionMatch = specContents.match(/\bversion:\s*([0-9-]+)/);
const openApiVersion = versionMatch?.[1] ?? "unknown";

const metadata = `// Generated by npm run generate:sdk. Do not edit manually.\n` +
  `export const OPENAPI_VERSION = "${openApiVersion}";\n` +
  `export const OPENAPI_SHA256 = "${openApiSha256}";\n`;

writeFileSync(metadataPath, metadata);

console.log(`OpenAPI version: ${openApiVersion}`);
console.log(`OpenAPI sha256: ${openApiSha256}`);
console.log("SDK metadata generated.");
